import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  type AttributeSpec,
  CrateReader,
  type PrimSpec,
  Stage,
  ThreeUsdRobotLoader,
  UsdMatrix,
  type UsdaFile,
  crateToUsdaFile,
  extractRobotDescription,
  parseUsda,
  serializeUsda,
} from "../src/index.js";
import { decodeRepBits } from "../src/usd/crate/valueTypes.js";

// M17: time samples stored inside binary crate files, plus decode hardening.
// The fixture pair is generated by scripts/make-crate-fixtures.py — one stage
// exported to both formats, so the two files are equivalent by construction.
const USDC = new URL("../test-assets/anim_arm.usdc", import.meta.url);
const USDA = new URL("../test-assets/anim_arm.usda", import.meta.url);

const usdcBytes = new Uint8Array(readFileSync(USDC));
const usdaText = readFileSync(USDA, "utf-8");

const crateAst = (): UsdaFile => crateToUsdaFile(new CrateReader(usdcBytes));

function findPrim(file: UsdaFile, path: string): PrimSpec | undefined {
  let prims = file.prims;
  let prim: PrimSpec | undefined;
  for (const seg of path.split("/").filter(Boolean)) {
    prim = prims.find((p) => p.name === seg);
    if (!prim) return undefined;
    prims = prim.children;
  }
  return prim;
}

function attrOf(file: UsdaFile, primPath: string, name: string): AttributeSpec | undefined {
  const prop = findPrim(file, primPath)?.properties.find((p) => p.name === name);
  return prop?.kind === "attribute" ? prop : undefined;
}

describe("crate timeSamples (test-assets/anim_arm)", () => {
  it("decodes attribute timeSamples identically to the USDA twin", () => {
    const crate = crateAst();
    const usda = parseUsda(usdaText);

    const drive = "drive:angular:physics:targetPosition";
    const fromCrate = attrOf(crate, "/World/j1", drive)?.timeSamples;
    const fromUsda = attrOf(usda, "/World/j1", drive)?.timeSamples;
    expect(fromCrate).toBeDefined();
    expect([...fromCrate!]).toEqual([
      [0, 0],
      [48, 90.5],
      [96, -30.25],
    ]);
    expect([...fromCrate!]).toEqual([...fromUsda!]);

    // Doubles that are not float32-representable → non-inlined sample reps.
    const dbl = attrOf(crate, "/World/base", "test:dbl")?.timeSamples;
    expect([...dbl!]).toEqual([
      [0, 0.1],
      [96, 0.2],
    ]);
  });

  it("decodes matrix4d samples (inlined identity + full scalar)", () => {
    const samples = attrOf(crateAst(), "/World/panel", "xformOp:transform")?.timeSamples;
    expect(samples?.size).toBe(2);
    const identity = samples?.get(0) as UsdMatrix;
    const moved = samples?.get(96) as UsdMatrix;
    expect(identity).toBeInstanceOf(UsdMatrix);
    expect(identity.values).toEqual(UsdMatrix.identity4().values);
    expect(moved.values.slice(12, 15)).toEqual([0.5, 0, 0.25]);
  });

  it("surfaces the layer's animation range and customLayerData", () => {
    const meta = crateAst().metadata;
    expect(meta.startTimeCode).toBe(0);
    expect(meta.endTimeCode).toBe(96);
    expect(meta.timeCodesPerSecond).toBe(24);
    expect(meta.customLayerData).toEqual({
      generator: "make-crate-fixtures",
      revision: 3,
      scale: 0.5,
    });
  });

  it("plays the animation from the binary crate (parity with USDA)", async () => {
    const fromCrate = await new ThreeUsdRobotLoader().parseCrate(usdcBytes);
    const fromUsda = await new ThreeUsdRobotLoader().parse(usdaText);

    expect(fromCrate.hasAnimation()).toBe(true);
    expect(fromCrate.getTimeRange()).toEqual({ start: 0, end: 96 });
    expect(fromCrate.getTimeCodesPerSecond()).toBe(24);

    const deg = Math.PI / 180;
    for (const [time, expected] of [
      [0, 0],
      [24, 45.25 * deg], // halfway to the 90.5° sample
      [48, 90.5 * deg],
      [96, -30.25 * deg],
    ] as const) {
      fromCrate.setTime(time);
      fromUsda.setTime(time);
      expect(fromCrate.getJointValue("j1")).toBeCloseTo(expected, 9);
      expect(fromUsda.getJointValue("j1")).toBeCloseTo(expected, 9);
    }
  });

  it("extracts an identical RobotDescription from both formats", () => {
    const fromCrate = extractRobotDescription(Stage.OpenFromFile(crateAst()));
    const fromUsda = extractRobotDescription(Stage.OpenFromString(usdaText));
    expect(fromCrate).toEqual(fromUsda);
    const samples = fromCrate.joints.j1?.valueSamples;
    expect(samples?.times).toEqual([0, 48, 96]);
    const degrees = [0, 90.5, -30.25];
    for (const [i, v] of (samples?.values ?? []).entries()) {
      expect(v).toBeCloseTo((degrees[i]! * Math.PI) / 180, 12);
    }
  });

  it("preserves timeSamples through usdc→usda conversion", () => {
    const out = serializeUsda({ ...crateAst(), version: "1.0" });
    expect(out).toContain("drive:angular:physics:targetPosition.timeSamples = {");
    expect(out).toContain("48: 90.5,");
    // Round-trip: the written text parses back to the same samples.
    const again = attrOf(parseUsda(out), "/World/j1", "drive:angular:physics:targetPosition");
    expect([...again!.timeSamples!]).toEqual([
      [0, 0],
      [48, 90.5],
      [96, -30.25],
    ]);
  });
});

describe("crate decode hardening (M17)", () => {
  const reader = new CrateReader(usdcBytes);
  const paths = reader.getPaths();
  const byPath = new Map(reader.getSpecs().map((s) => [paths[s.pathIndex]!, s]));
  const fieldVal = (path: string, name = "default") => {
    const spec = byPath.get(path);
    if (!spec) return undefined;
    for (const fi of reader.getFieldSet(spec.fieldSetIndex)) {
      const f = reader.getFields()[fi]!;
      if (reader.getToken(f.nameIndex) === name) return reader.getValue(f.rep);
    }
    return undefined;
  };

  it("decodes an inlined Vec3d (int8-packed components)", () => {
    expect(fieldVal("/World/arm.xformOp:translate")).toEqual([1, 2, 3]);
  });

  it("decodes uchar arrays", () => {
    expect(fieldVal("/World/base.test:uchars")).toEqual([0, 1, 127, 255]);
  });

  it("decodes compressed float arrays (code 'i': all-integral)", () => {
    expect(fieldVal("/World/base.test:intFloats")).toEqual([...Array(20).keys()]);
  });

  it("decodes compressed float arrays (code 't': lookup table)", () => {
    expect(fieldVal("/World/base.test:lutFloats")).toEqual(
      Array.from({ length: 20 }, (_, i) => (i % 2 === 0 ? 0.5 : 1.5)),
    );
  });

  it("keeps the custom flag on custom attributes", () => {
    expect(attrOf(crateAst(), "/World/base", "test:uchars")?.custom).toBe(true);
    expect(attrOf(crateAst(), "/World/j1", "physics:axis")?.custom).toBe(false);
  });
});

// Regression against a real Isaac-exported crate: every field of the formerly
// undecodable types must now produce a value. Skipped when the large asset is
// absent (it is not committed).
const TOROBO = new URL("../data/torobo2_standard_planar_move.usd", import.meta.url);

describe.skipIf(!existsSync(TOROBO))("crate decode hardening (data/torobo2)", () => {
  it("decodes every inlined-vec / uchar[] / dictionary field", () => {
    const reader = new CrateReader(new Uint8Array(readFileSync(TOROBO)));
    const hardened = new Set([2 /* UChar */, 23 /* Vec3d */, 31 /* Dictionary */]);
    let checked = 0;
    for (const field of reader.getFields()) {
      const bits = decodeRepBits(field.rep);
      if (!hardened.has(bits.type)) continue;
      checked++;
      expect(
        reader.getValue(field.rep),
        `field ${reader.getToken(field.nameIndex)} (type ${bits.type})`,
      ).toBeDefined();
    }
    expect(checked).toBeGreaterThan(0);
  });
});
